"""cooper points table

Revision ID: 14586d42fcd4
Revises: 3bcf330e030c
Create Date: 2024-06-17 13:27:35.788022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migrations.data.bike_points import BIKE_POINTS
from migrations.data.run_points import RUN_POINTS
from migrations.data.swim_points import SWIM_POINTS
from migrations.data.walk_points import WALK_POINTS


# revision identifiers, used by Alembic.
revision: str = "14586d42fcd4"
down_revision: Union[str, None] = "3bcf330e030c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cooper_table = op.create_table(
        "cooper_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity", sa.String(), nullable=False),
        sa.Column("distance_floor", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("lowest_time", sa.Time(), nullable=False),
        sa.Column("highest_time", sa.Time(), nullable=False),
        sa.Column("points", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cooper_points")),
    )
    # After creating table, can run the inserts to load static data
    op.bulk_insert(cooper_table, WALK_POINTS + RUN_POINTS + BIKE_POINTS + SWIM_POINTS)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cooper_points")
    # ### end Alembic commands ###
