"""add activity type constraint and distance_yard col

Revision ID: 14c93f4b3453
Revises: 89eae62594f6
Create Date: 2024-06-06 10:50:40.399382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14c93f4b3453"
down_revision: Union[str, None] = "89eae62594f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "runs",
        "distance_mi",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.create_check_constraint(
        "correct_metric_for_activity_type",
        "runs",
        "(activity_type = 'swim' AND distance_yard IS NOT NULL AND distance_mi IS NULL) OR (activity_type != 'swim' AND distance_yard IS NULL AND distance_mi IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("correct_metric_for_activity_type", "runs", type_="check")
    op.alter_column(
        "runs",
        "distance_mi",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
    )
    # ### end Alembic commands ###
