"""credentials foreign key

Revision ID: 3afbddd0acf7
Revises: 35689311a20f
Create Date: 2024-04-17 10:33:09.830891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afbddd0acf7'
down_revision: Union[str, None] = '35689311a20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'credentials', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.drop_column('credentials', 'user_id')
    # ### end Alembic commands ###
