"""add cooper points to runs

Revision ID: 3bcf330e030c
Revises: 14c93f4b3453
Create Date: 2024-06-17 10:14:11.504401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3bcf330e030c"
down_revision: Union[str, None] = "14c93f4b3453"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", recreate="always") as batch_op:
        batch_op.add_column(
            sa.Column(
                "cooper_points",
                sa.Numeric(precision=5, scale=2),
                nullable=False,
                server_default="0.00",
            ),
            insert_after="notes",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "cooper_points")
    # ### end Alembic commands ###
