"""allow non unique email col

Revision ID: f99ef9488ac6
Revises: 3d10732bc6e4
Create Date: 2024-07-04 10:02:11.301725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99ef9488ac6'
down_revision: Union[str, None] = '3d10732bc6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_credentials_user_id'), 'credentials', ['user_id'])
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_constraint(op.f('uq_credentials_user_id'), 'credentials', type_='unique')
    # ### end Alembic commands ###
